# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-08 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newscollector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 8, 7, 7, 53, 585181, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
