# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-08 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscollector', '0002_auto_20180808_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_short',
            field=models.TextField(blank=True),
        ),
    ]
