# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-08 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newscollector', '0004_auto_20180808_1242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('title', 'date', 'origin_link', 'link')]),
        ),
    ]
