# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-10 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newscollector', '0005_auto_20180808_1347'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('title', 'date', 'link')]),
        ),
    ]
