# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newscollector', '0006_auto_20180810_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('rss', 'RSS-feed'), ('html', 'Html page'), ('google-news', 'Google News API'), ('yandex-news', 'Yandex News API')], default='rss', max_length=64)),
                ('link', models.URLField()),
                ('last_checked', models.DateTimeField(null=True)),
                ('image', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='origin_link',
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='newscollector.NewsSource'),
            preserve_default=False,
        ),
    ]
